# This downloads the minimal image ubuntu 14.04 (trusty, x86_64)
# Author: askb23@gmail.com
# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile API/syntax version.
#
# Pre-req:
# Install VirtualBox, Vagrant
# Install plugin vagrant-hostmanager
# $ sudo vagrant plugin install vagrant-hostmanager

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = false
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "/myVMs/shared", "/shared", disabled: false, mount_options: ["dmode=777", "fmode=666"]

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 6080, host: 6080

# devstack: controller and compute node (all services)

  config.vm.define "devstack" do |devstack|

    devstack.vm.network :private_network, ip: "10.0.1.10"
    devstack.vm.network :private_network, ip: "10.15.15.101"

    devstack.vm.hostname = "devstack.mycloud.in"
    devstack.hostmanager.aliases = %w(devstack)
        devstack.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--memory", "6144"]
          v.customize ["modifyvm", :id, "--cpus", "2"]
          v.gui = false
        end
  end

  config.vm.provision "shell", inline: <<-SHELL
       sudo pip install --upgrade pip
       sudo pip install -U os-testr
  SHELL

  config.vm.provision "file", source: "~/.gitconfig", destination:  "~/.gitconfig"
  config.vm.provision "file", source: "./local.conf", destination:  "~/local.conf"

  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
  #   sudo apt-get install -y puppet-common vim git
  #   sudo apt-get install -y virtualbox-guest-utils virtualbox-guest-x11 virtualbox-guest-dkms
     sudo apt-get install -y git
     sudo apt-get install -y wget
     sudo apt-get install -y python-pip
     sudo apt-get install -y python-dev
  SHELL

  config.vm.provision "shell", path: './provision.sh', privileged: false
end
